name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '25'
      - uses: gradle/actions/setup-gradle@v6

      - run: ./gradlew build
      - run: ./gradlew test
      - run: ./gradlew :black-cli:run --args='check .'
